### PR TITLE
Improve building instructions

### PR DESCRIPTION
**Pull request by lykahb**
More detailed instructions make it easier to build the project for someone who is not very familiar with the C toolchain. Hopefully, an advanced user who is not a developer can build it it too. By the way, would you be interested in publishing the binaries on the github release page?

### CODE REVIEW

**Comment by mls-m5** [comment]
Nice changes.

Some comments

This code:
```
git submodule update --init --recursive
cmake .
make
```

Should be
```
git submodule update --init --recursive
mkdir build
cd build
cmake ..
make
```
(By convention to not mix up build files and source files)

Do you want to update it to preserve your data change history, or should I do it?

Publishing binaries is a good idea I might add that in a while if you are not interested in doing it.

I love neotools btw. Great library! :)

**Comment by lykahb** [comment]
Thanks for the explanation, updated the PR. I'm not familiar with the C or C++ conventions and usually just call `make`. I was surprised though that the commands I ran put the build files on the root level.

**Comment by mls-m5** [comment]
Yes I agree, it's one of those kinks of using cmake. I would prefer if it just put it in the build directory automatically. It's somewhat functional when you want to have two different types of builds (for example build and release) but if you just want to build it's just extra steps.

Thanks for your contribution anyways, and feel free to send a message/pr/issue if you have any more thoughts.

**Comment by mls-m5** [comment]
@lykahb Hey. Just wanted to say that I have experimenting with generating binaries. I managed to get the linux ones to work, but the windows and mac ones seems impossible.

**Comment by lykahb** [comment]
@mls-m5 There is also a crazy idea of building for wasm. Then the neo-font-editor could work as a static web page. The applets can be uploaded and downloaded as files. And the font can be simply a textarea.

**Comment by mls-m5** [comment]
@lykahb That idea is pretty good :)

**Pull request merged**
